using System;
using System.Windows.Forms;

namespace WindowsFormsApp2
{
    // Define a partial class named Form1 within the WindowsFormsApp2 namespace
    public partial class Form1 : Form
    {
        // Declare a private variable to store the components of the form
        private System.ComponentModel.IContainer components = null;

        // Constructor for the Form1 class
        public Form1()
        {
            // Call the InitializeComponent method to initialize the components
            InitializeComponent();
        }

        // Method to clean up any resources used by the form
        protected override void Dispose(bool disposing)
        {
            // Check if disposing is true and components is not null
            if (disposing && (components != null))
            {
                // Dispose of all components
                components.Dispose();
            }
            // Call the base Dispose method
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        // Method generated by the Windows Form Designer to initialize the components
        private void InitializeComponent()
        {
            // Initialize the buttons, RichTextBox, TextBox, and PictureBox
            this.button3 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.button4 = new System.Windows.Forms.Button();
            this.ControlePanel = new System.Windows.Forms.RichTextBox();
            this.commandline = new System.Windows.Forms.TextBox();
            this.display = new System.Windows.Forms.PictureBox();

            // Set properties for the buttons
            this.button3.Location = new System.Drawing.Point(18, 367);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(270, 23);
            this.button3.TabIndex = 0;
            this.button3.Text = "Run";
            this.button3.UseVisualStyleBackColor = true;
            this.button2.Location = new System.Drawing.Point(18, 427);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(95, 23);
            this.button2.TabIndex = 1;
            this.button2.Text = "Save";
            this.button2.UseVisualStyleBackColor = true;
            this.button4.Location = new System.Drawing.Point(181, 427);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(107, 23);
            this.button4.TabIndex = 2;
            this.button4.Text = "Clear";
            this.button4.UseVisualStyleBackColor = true;

            // Set properties for the RichTextBox and TextBox
            this.ControlePanel.Location = new System.Drawing.Point(18, 25);
            this.ControlePanel.Name = "ControlePanel";
            this.ControlePanel.Size = new System.Drawing.Size(270, 257);
            this.ControlePanel.TabIndex = 3;
            this.commandline.Location = new System.Drawing.Point(18, 311);
            this.commandline.Name = "commandline";
            this.commandline.Size = new System.Drawing.Size(270, 22);
            this.commandline.TabIndex = 4;

            // Set properties for the PictureBox
            this.display.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.display.Location = new System.Drawing.Point(316, 25);
            this.display.Name = "display";
            this.display.Size = new System.Drawing.Size(499, 436);
            this.display.TabIndex = 5;
            this.display.TabStop = false;
        }

        #endregion

        // Event handler for the Run button click event
        private void button3_Click(object sender, EventArgs e)
        {
            // Add code to handle the Run button click event
        }

        // Event handler for the Save button click event
        private void button2_Click(object sender, EventArgs e)
        {
            // Add code to handle the Save button click event
        }

        // Event handler for the Clear button click event
        private void button4_Click(object sender, EventArgs e)
        {
            // Add code to handle the Clear button click event
        }

        // Event handler for the KeyDown event of the TextBox
        private void Commandline_KeyDown(object sender, KeyEventArgs e)
        {
            // Add code to handle the KeyDown event of the TextBox
        }
    }
}


